import transporter from "../config/email.js";
import dotenv from "dotenv";
dotenv.config();

// Send enquiry details to Placerly (Admin Inbox)

 const sendEnquiryMailToPlacerly = async (enquiry) => {
  const html = `
    <div style="font-family: Arial, sans-serif; color: #333">
      <h2>📩 New Enquiry Received</h2>
      <p><strong>Name:</strong> ${enquiry.name}</p>
      <p><strong>Email:</strong> ${enquiry.email}</p>
      <p><strong>Subject:</strong> ${enquiry.subject}</p>
      <p><strong>Message:</strong><br/>${enquiry.message}</p>
      <hr style="margin-top:20px;border:none;border-top:1px solid #ccc;"/>
      <p style="font-size:13px;color:#777;">This message was automatically generated by Placerly’s website.</p>
    </div>
  `;

  return await transporter.sendMail({
    from: `"Placerly" <${process.env.EMAIL_FROM}>`,
    to: process.env.ADMIN_EMAIL,
    subject: `New Enquiry from ${enquiry.name}`,
    html,
  });
};



// Send confirmation mail to User

 const sendEnquiryMailToUser = async (userEmail, enquiry) => {
  const html = `
    <div style="background: linear-gradient(135deg, #0B1F3A, #0A1526, #08101D); padding: 30px; border-radius: 12px; color: #fff;">
      <h2 style="margin-top: 0;">Hello ${enquiry.name},</h2>
      <p>Thank you for contacting <strong>Placerly</strong>! 💬</p>
      <p>We’ve received your enquiry and our support team will get back to you soon.</p>

      <div style="margin-top: 20px; background: rgba(255,255,255,0.05); padding: 15px; border-radius: 8px;">
        <p style="margin:0;"><strong>Name:</strong> ${enquiry.name}</p>
        <p style="margin:0;"><strong>Email:</strong> ${enquiry.email}</p>
        <p style="margin:0;"><strong>Subject:</strong> ${enquiry.subject}</p>
        <p style="margin:0;"><strong>Your Message:</strong> ${enquiry.message}</p>
      </div>

      <p style="margin-top: 20px;">Best Regards,<br/><strong>The Placerly Team</strong></p>

      <p style="margin-top: 10px; font-size: 12px; color: #9DB8D6;">
        This is an automated message. Please don’t reply directly to this email.
      </p>
    </div>
  `;

  return await transporter.sendMail({
    from: `"Placerly Support" <${process.env.EMAIL_FROM}>`,
    to: userEmail,
    subject: `We’ve received your enquiry - ${enquiry.subject}`,
    html,
  });
};

export { sendEnquiryMailToPlacerly, sendEnquiryMailToUser };
